name: Build and Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Write key
      run: |
        if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
          {
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}'
            echo keyPassword='${{ secrets.KEY_PASSWORD }}'
            echo keyAlias='${{ secrets.KEY_ALIAS }}'
            echo storeFile='../keystore.jks'
          } > keystore.properties
          echo '${{ secrets.KEYSTORE }}' | base64 -d > keystore.jks
        fi

    # Tạo thư mục rỗng thay thế cho phần tài liệu bị lỗi để Gradle build mượt mà
    - name: Create dummy assets directory
      run: |
        mkdir -p ./app/src/main/assets/XtMapper-docs
        touch ./app/src/main/assets/XtMapper-docs/.gitkeep

    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: 'app/build/outputs/apk/release/*.apk'
        asset_name: app-release.zip
        tag: ${{ github.ref_name }}
        overwrite: true
        file_glob: true          
        draft: true
